[package]
name = "punfetch"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sysinfo = "0.27.2"
colored = "2.0.0"
byte-unit = "4.0.18"
onefetch-image = "2.14.2"
image = "0.24.5"
color-thief = "0.2.2"
humantime = "2.1.0"
clap = { version = "4.0.32", features=["cargo"] }
