[package]
name = "punfetch-derive"
version = "0.1.0"
authors = ["ossian <self@ossian.dev>"]
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = "1"

[dev-dependencies]
owo-colors = "3.5.0"
punfetch = { path = "../." }
